### ISSUE TITLE
"FacedancerApp failed to autodetect any Facedancer devices" for usbproxy sample

### ISSUE THREAD

**Issue by dominikfehr** [greatscottgadgets/cynthion#163]
BACKEND environment is set

cynthion info --force-offline returns:

`Cynthion version: 0.1.3
Apollo version: 1.1.0
Python version: 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]

Found Apollo stub interface!
	Bitstream: Facedancer (Cynthion Project)
	Vendor ID: 1d50
	Product ID: 615b
	bcdDevice: 0104
	Bitstream serial number: 332a54cba3ac60de

Forcing offline.

Found Cynthion device!
	Hardware: Cynthion r1.4
	Manufacturer: Great Scott Gadgets
	Product: Cynthion Apollo Debugger
	Serial number: ZN7QSDKMGJJVCIBAEA3DSIIO74
	Vendor ID: 1d50
	Product ID: 615c
	bcdDevice: 0104
	Firmware version: v1.1.0
	USB API version: 1.2
	Flash UID: 332a54cba3ac60de
`

**Comment by c8rri3r** [comment]
I had the same error message when trying to run the `hackrf_emulation.py` script  from the [Emulation of a USB Device](https://cynthion.readthedocs.io/en/latest/tutorials/emulation.html) page, despite the `cynthion info --force-offline` command indicating everything was setup correctly and updating cynthing/facedancer to the latest versions with pip. 

(This consistently failed on Windows 11 x64, Linux ARM64, and WSL Linux x64).

```bash
$ export BACKEND=cynthion ; python3 hackrf_emulation.py
INFO    | __init__       | Starting emulation, press 'Control-C' to disconnect and exit.
WARNING | moondancer     | Found Cynthion-based device, but could not access it. (Check permissions?)
INFO    | hydradancer    | this is hydradancer hi
ERROR   | core           | FacedancerApp failed to autodetect any Facedancer devices.
ERROR   | core           | Try specifying a backend with: BACKEND="<backend name>" <your app>
Traceback (most recent call last):
File "/home/projects/cynthion/hackrf_emulation.py", line 16, in <module>
main(HackRF)                                                               
...
 File "/home/venv/cynthia/lib/python3.11/site-packages/facedancer/core.py", line 58, in autodetect
    raise DeviceNotFoundError("FacedancerApp failed to autodetect any Facedancer devices.")
facedancer.errors.DeviceNotFoundError: FacedancerApp failed to autodetect any Facedancer devices.
```

The solution was to run `cynthion run facedancer` as mentioned on the [Getting Started Facedancer](https://cynthion.readthedocs.io/en/latest/getting_started_facedancer.html) page. 

After that, facedancer was able to find the device and it started working. 

```bash
$ export BACKEND=cynthion ; python3 hackrf_emulation.py
INFO    | __init__       | Starting emulation, press 'Control-C' to disconnect and exit.
INFO    | moondancer     | Using the Moondancer backend.
INFO    | moondancer     | Connected FULL speed device '__main__.HackRF' to target host.
INFO    | device         | Host issued a bus reset; resetting our connection.
```
