### ISSUE TITLE
Facedancer unit tests fail when emulated device and tests are being run on the same host.

### ISSUE THREAD

**Issue by antoinevg** [greatscottgadgets/cynthion#200]
Example:

```
(gsg-cynthion-dev) work:facedancer.git % python -m unittest
....E
======================================================================
ERROR: test_control_out_transfer (test.test_transfers.TestTransfers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/antoine/GreatScott/facedancer.git/test/test_transfers.py", line 95, in test_control_out_transfer
    bytes_sent = self.control_out_transfer(data)
  File "/Users/antoine/GreatScott/facedancer.git/test/base.py", line 68, in control_out_transfer
    response = self.device_handle.controlWrite(
  File "/Users/antoine/.pyenv/versions/gsg-cynthion-dev/lib/python3.9/site-packages/usb1/__init__.py", line 1330, in controlWrite
    return self._controlTransfer(request_type, request, value, index, data,
  File "/Users/antoine/.pyenv/versions/gsg-cynthion-dev/lib/python3.9/site-packages/usb1/__init__.py", line 1307, in _controlTransfer
    mayRaiseUSBError(result)
  File "/Users/antoine/.pyenv/versions/gsg-cynthion-dev/lib/python3.9/site-packages/usb1/__init__.py", line 127, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/Users/antoine/.pyenv/versions/gsg-cynthion-dev/lib/python3.9/site-packages/usb1/__init__.py", line 119, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorTimeout: LIBUSB_ERROR_TIMEOUT [-7]

----------------------------------------------------------------------
Ran 5 tests in 2.037s

FAILED (errors=1)
(gsg-cynthion-dev) work:facedancer.git %
```

**Comment by martinling** [comment]
Running `test.device` on Linux and `unittest` on macOS *mostly* passes, but fails about 2/10 times.

Swapping those roles, the test fails every time.
